server:
  port: 8888

spring:
  datasource:
    url: jdbc:mysql://8.130.76.145:3306/yutu?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: Hjf33770088++
  redis:
    host: 8.138.88.67
    port: 6379
    password: 1234
    database: 2
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
  banner:
    location: banner.txt
    charset: UTF-8

mybatis-plus:
  type-aliases-package: com.yutu.entity # 别名扫描包
  global-config:
    banner: false
logging:
  level:
    com.yutu: debug

# 阿里云OSS的密钥
yutu:
  alioss:
    endpoint: oss-cn-guangzhou.aliyuncs.com
    access-key-id: LTAI5t88UuzJc2E1YqnSvqum
    access-key-secret: zDF5BWs7I0ZUsS3l9QHGFuHuHpRgtq
    bucket-name: yutu-408